# Explore the utility of boolean arrays

In [2]:
import numpy as np

### Create a 2D array we can play with

In [3]:
data_1D = np.arange(12)
data_2D = data_1D.reshape((3,4))
print(data_2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Which elements are even numbers?

In [4]:
is_even = data_2D%2 == 0
print(is_even)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


### Extract the even elements

In [5]:
even_elements = data_2D[is_even]
print(even_elements)

[ 0  2  4  6  8 10]


## Now you try:
### Can you extract elements divisible by 3?

In [ ]:
is_divisible = 
divisible_elements = 
print(divisible_elements)

## Condition statements with Boolean arrays

In [6]:
if is_even.any():
    print("Array contains at least one even number")
else:
    print("Array has no even numbers")

Array contains at least one even number


In [7]:
if is_even.all():
    print("Array is entirely made of even numbers")
else:
    print("Some or all of the array elements are not even")

Some or all of the array elements are not even
