# Common ways of creating arrays

In [1]:
import numpy as np

### From existing data

In [3]:
data_1D = np.array([7.21,80,9.5,3,11,93.7])
print(data_1D)

[  7.21  80.     9.5    3.    11.    93.7 ]


In [5]:
data_2D = np.array([ [5,6.8,9], [10,3,4.5], [8.1,2,13] ])
print(data_2D)

[[  5.    6.8   9. ]
 [ 10.    3.    4.5]
 [  8.1   2.   13. ]]


### All ones or zeros

In [6]:
ones_1D = np.ones(15)
print(ones_1D)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [8]:
zeros_3D = np.zeros( (3,3,3) )
print(zeros_3D)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


### Array of random numbers

Sample a uniform distribution between 0 and 1

In [25]:
print(np.random.rand(3,3))

[[ 0.78096421  0.26805973  0.2460926 ]
 [ 0.58141486  0.27697552  0.58434393]
 [ 0.57067294  0.07064347  0.72981669]]


Sample the standard normal distribution

In [26]:
print(np.random.randn(3,3))

[[-0.74564529 -0.15896728  1.09956378]
 [ 0.18371958  1.17173988  0.28360414]
 [-0.38484171  1.22322165 -1.37982966]]


### Using `arange` and `linspace`

`np.arange` can take 1, 2, or 3 arguments

In [9]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(np.arange(5,10))

[5 6 7 8 9]


In [13]:
print(np.arange(1,10,3))

[1 4 7]


We can also count backwards:

In [18]:
print(np.arange(10,1,-3))

[10  7  4]


`np.linspace` must take at least 2 arguments, but will also accept a third.

In [16]:
l = np.linspace(10,20)
print(l)
print("Size:", l.size)

[ 10.          10.20408163  10.40816327  10.6122449   10.81632653
  11.02040816  11.2244898   11.42857143  11.63265306  11.83673469
  12.04081633  12.24489796  12.44897959  12.65306122  12.85714286
  13.06122449  13.26530612  13.46938776  13.67346939  13.87755102
  14.08163265  14.28571429  14.48979592  14.69387755  14.89795918
  15.10204082  15.30612245  15.51020408  15.71428571  15.91836735
  16.12244898  16.32653061  16.53061224  16.73469388  16.93877551
  17.14285714  17.34693878  17.55102041  17.75510204  17.95918367
  18.16326531  18.36734694  18.57142857  18.7755102   18.97959184
  19.18367347  19.3877551   19.59183673  19.79591837  20.        ]
Size: 50


In [17]:
l = np.linspace(10,20,30)
print(l)
print("Size:", l.size)

[ 10.          10.34482759  10.68965517  11.03448276  11.37931034
  11.72413793  12.06896552  12.4137931   12.75862069  13.10344828
  13.44827586  13.79310345  14.13793103  14.48275862  14.82758621
  15.17241379  15.51724138  15.86206897  16.20689655  16.55172414
  16.89655172  17.24137931  17.5862069   17.93103448  18.27586207
  18.62068966  18.96551724  19.31034483  19.65517241  20.        ]
Size: 30


`linspace` will also run backwards:

In [20]:
print(np.linspace(20,10,30))

[ 20.          19.65517241  19.31034483  18.96551724  18.62068966
  18.27586207  17.93103448  17.5862069   17.24137931  16.89655172
  16.55172414  16.20689655  15.86206897  15.51724138  15.17241379
  14.82758621  14.48275862  14.13793103  13.79310345  13.44827586
  13.10344828  12.75862069  12.4137931   12.06896552  11.72413793
  11.37931034  11.03448276  10.68965517  10.34482759  10.        ]
