# Linear Algebra in NumPy

Through a lot of these examples, we've been treating NumPy arrays as data containers. But we can also treat them like vectors and matrices.

NumPy provides support for linear algebra operations both within NumPy and its sub-module `linalg`.

In [1]:
import numpy as np
import numpy.linalg as la

First we make matrices and vectors to play with:

In [2]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4]])
M = np.array([[1,2],[3,4]]) # square matrix
a = np.array([4,5,6])
b = np.array([7,8,9])
v = np.array([5,6])

## Transpose

We can transpose an array using `.T`:

In [3]:
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


It has no affect on 1D arrays

In [4]:
print(a)
print(a.T)

[4 5 6]
[4 5 6]


## Multiplication

The `np.dot` function (and its cousin, the `.dot` method) is very flexible and will combine any two `ndarray`s of any dimension. See [the documentation.](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

### Vector Dot Product

Dot products should be commutative.

In [5]:
print(np.dot(a,b))
print(np.dot(b,a))

122
122


In [6]:
print(a.dot(b))
print(b.dot(a))

122
122


### Vector-Matrix Multiplication

This operation is not commutative, just as we expect.

In [7]:
print(np.dot(A,a))

[32 77]


In [8]:
print(np.dot(a,A))

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

When using the `.dot` method, the object to which the method belongs is on the left of the equation:

In [9]:
print(A.dot(a))

array([32, 77])

### Matrix-Matrix Multiplication

Once again, this operation is not commutative, as we expect.

In [10]:
print(np.dot(B,A))

array([[ 9, 12, 15],
       [19, 26, 33]])

In [11]:
print(B.dot(A))

array([[ 9, 12, 15],
       [19, 26, 33]])

In [12]:
print(A.dot(B))

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

The `dot` function is very general, and therefore slower at matrix multiplication than the specialized `matmul` function. We'll see this using the `%%timeit` notebook "magic" function.

In [13]:
%%timeit
np.dot(B,A)

596 ns ± 8.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
%%timeit
np.matmul(B,A)

1.12 µs ± 51.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Solving Matrix Equations $Mx=v$

Now we'll start using functions from the `linalg` module, which we imported as `la`.

In [15]:
x = la.solve(M,v)
print(x)

[-4.   4.5]


## Inverting Square Matrices

In [16]:
Minv = la.inv(M)
print(Minv.dot(M))
print(M.dot(Minv))

[[  1.00000000e+00   4.44089210e-16]
 [  0.00000000e+00   1.00000000e+00]]
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


## Eigenvalues and Eigenvectors

In [17]:
evals, evecs = np.linalg.eig(M)
print(evals.shape)
print(evecs.shape)

(2,)
(2, 2)


Each column of `evecs` corresponds to the eigevalues in `evals`.

In [18]:
vec = evecs[:,0]
print(M.dot(vec))
print(evals[0] * vec)

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


## Matrix Norms

We can compute several different matrix norms. The default is the Frobenius 2-norm

In [19]:
print(la.norm(M))

5.4772255750516612

We could also specify the infinity-norm:

In [20]:
print(la.norm(M, ord=np.inf))

7.0