# Getting statistical information from arrays

There are many functions in NumPy that respond the same way to function arguments:
- `np.sum` adds array elements
- `np.prod` multiplies array elements
- `np.mean` calculates the arithmetic mean
- `np.average` can gives you a weighted average. If no weights are supplied, which is the default, it behaves just like np.mean
- `np.median` calculates the median
- `np.std` gives the standard deviation
- `np.var` calculates the variance

We will introduce their behavior using `np.sum`.

In [1]:
# Make some data
data_2D = np.arange(9).reshape(3,3)
print(data_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
data_3D = np.arange(12).reshape(2,2,3)
print(data_3D)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### With no additional arguments:

In [3]:
print(np.sum(data_2D))

36


In [4]:
print(np.sum(data_3D))

66


### Specifying an axis:

2D

In [5]:
# Sum along Columns
print(np.sum(data_2D, 0))

[ 9 12 15]


In [6]:
# Sum along Rows
print(np.sum(data_2D, 1))

[ 3 12 21]


3D

In [7]:
# Sum all Slabs
print(np.sum(data_3D, 0))

[[ 6  8 10]
 [12 14 16]]


In [8]:
# Sum along columns, so each 2D slab becomes a 1D array
print(np.sum(data_3D, 1))

[[ 3  5  7]
 [15 17 19]]


In [9]:
# Ditto but with rows
print(np.sum(data_3D, 2))

[[ 3 12]
 [21 30]]


## Trying the other functions

In [10]:
# Scramble the array of numbers from 0-9
test_2D = np.arange(9)
np.random.shuffle(test_2D)
test_2D = np.reshape(test_2D, (3,3))
print(test_2D)

[[8 4 3]
 [6 5 1]
 [0 2 7]]


In [11]:
test_3D = np.arange(12)
np.random.shuffle(test_3D)
test_3D = np.reshape(test_3D, (2,2,3))
print(test_3D)

[[[11  4  6]
  [ 3  9 10]]

 [[ 7  2  8]
  [ 0  1  5]]]


In [12]:
print(np.mean(test_2D))

4.0


In [13]:
print(np.mean(test_2D,0))

[ 4.66666667  3.66666667  3.66666667]


In [14]:
print(np.std(test_2D,0))

[ 3.39934634  1.24721913  2.49443826]


In [15]:
print(np.mean(test_3D,0))

[[ 9.   3.   7. ]
 [ 1.5  5.   7.5]]


## Now you try it
### Play around with both 2D and 3D data